pipeline {
  agent {
    kubernetes {
              yaml """
        apiVersion: v1
        kind: Pod
        metadata:
          labels:
            name: gradle
        spec:
          containers:
          - name: gradle
            image: gradle:6.3.0-jdk11
            command:
            - cat
            tty: true
            env:
              # Define the environment variable
              - name: CRED
                valueFrom:
                  configMapKeyRef:
                    name: jenkinscred
                    key: ECR_CREDENTIAL_JSON
          restartPolicy: Never
        """      
    }
  }
  
  stages {
    stage('build and push docker image') {
                  
      steps {
        container('gradle') {
          dir('eshop-adservice') {
            sh 'gradle jib --no-daemon --image 566478607909.dkr.ecr.us-east-1.amazonaws.com/eshop-adservice/eshop-adservice:0.0.1 -Djib.to.auth.username=AWS -Djib.to.auth.password=$CRED'  
          }
        }
      }
    }
  }
}
