pipeline {
  agent {
    kubernetes {
      yaml '''
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
'''
    }
  }
  environment {
    IMAGE_REGISTRY = '566478607909.dkr.ecr.us-east-1.amazonaws.com'
  }
  stages {
    stage('Build with Kaniko') {
      steps {
        container(name: 'kaniko', shell: '/busybox/sh') {
          dir('eshop-frontend') {
            // Set up the environment variable CRED from the ConfigMap
            script {
              // Export the credentials to a temporary file
              sh '''
                echo $CRED > /kaniko/ecr_credentials.json
              '''
            }
            // Build and push with Kaniko
            sh '''#!/busybox/sh
            /kaniko/executor \
            --git branch=main \
            --context=. \
            --destination=${IMAGE_REGISTRY}/eshop-frontend:0.0.1
            '''
          }
        }
      }
    }
  }
}
